### PR TITLE
feat: replace usage of `ref(markRaw(...))` width `shallowRef(...)`

### PR DESCRIPTION
**Pull request by pdanpdan**
ref https://github.com/vikejs/vike-vue/pull/129#issuecomment-2165561961

### CODE REVIEW

**Comment by brillout** [comment]
Neat, much cleaner. Can you remove `feat: `? Or replace it with `perf: ` if you believe it's a performance boost. The only goal of the prefix is to generate `CHANGELOG.md` entries.

**Comment by pdanpdan** [comment]
It's more chore:

**Comment by brillout** [comment]
Yea, let's not add any prefix then.

**Comment by brillout** [comment]
We don't use `chore: `.

**Comment by pdanpdan** [comment]
done

**Comment by brillout** [comment]
:sparkles:

**Pull request merged**
