### PR TITLE
feat: Vike vue/add stream setting

### PR DESCRIPTION
**Pull request by phonzammi**
Hi @AurelienLourot ,
Allow me to also add stream setting to vike-vue

### CODE REVIEW

**Comment by AurelienLourot** [comment]
Released as `0.5.1`

**Comment by AurelienLourot** [comment]
Awesome, thanks a lot for all the contributions @phonzammi!

**Comment by AurelienLourot** [comment]
@phonzammi would you be up for implementing that in https://github.com/vikejs/vike-solid too? Feel free to say no if you don't have time at the moment :pray:

**Comment by phonzammi** [comment]
Sure, let me take a look 👀

**Pull request merged**
