### PR TITLE
ClientOnly component with Suspense and dynamic import

### LINKED ISSUE #27: `<ClientOnly>` Component
Since `vike-react` now has a [`<ClientOnly>` component](https://github.com/vikejs/vike-react/pull/35), it would be great to align `vike-vue` to also have such component.

### PR DESCRIPTION
**Pull request by 4350pChris**
closes #27 

I tried my hand at a `ClientOnly` component that uses dynamic imports.

Let me know what you think.

### CODE REVIEW

**Comment by brillout** [comment]
Neat, looks good. I'm not that familiar with Vue so I can't say much around that, but conceptually this LGTM.

Would you be up for adding a usage example at `/examples/basic/`? I'd be curious to see how `slots.fallback` works from the user perspective.

Let us know if you are up for writing the docs for it at https://vike.dev/ClientOnly#vue (but we can also do it ourselves, as you wish).

**Comment by 4350pChris** [comment]
Yeah, I'll do all those things, I might need a couple of days though.
I've decided to publish it as a separate package as well at https://github.com/4350pChris/vue-dynamic-client-only
We **could** use that package here, although I'd suspect you'd rather not have such dependencies, which I'd agree with.
There I've got an example as well, which I was using to test it. If you're curious right now, take a look at that. I'm using template slots here, since that's more aligned with how most people use vue - the `fallback` slot came from my first implementation where I had been using vue's `Suspense` component, which has that exact slot name, so I figured I'd mirror that API since we're doing something that's very similar here.

So you end up having

```vue
<ClientOnly :load="() => import("./MyComponent.vue")>
  <template #fallback>
    Loading...
  </template>
</ClientOnly>
```

Also, the component is transparent as it has only one root level component (which is the dynamic `component`) which means that any props / event listeners on `ClientOnly` are automatically passed to the component that `load` resolves to.

**Comment by brillout** [comment]
Nice, makes sense, and LGTM.

> Yeah, I'll do all those things, I might need a couple of days though.

👍 Looking forward to it. (No rush though.)

**Comment by 4350pChris** [comment]
Maybe wait until tomorrow, I'll try using `import.meta.env` instead of `onMounted` as there's some content flashing right now when switching between the components.
Maybe that'll fix it.

**Comment by brillout** [comment]
👍

**Comment by 4350pChris** [comment]
So, I tried and I'm getting `import.meta may appear only with 'sourceType: "module"`
I'm not sure but I think this happens because we transpile to commonjs.
So for now, using `import.meta.env.SSR` doesn't seem to be a viable alternative.
With that being said, LGTM

**Comment by 4350pChris** [comment]
I added one last thing, which I find important - `ClientOnly` should imo accept a default slot as well, in case we don't want to dynamically import the component for whatever reason.

Let me know if you think that's a bad idea. But I think we should leave it up to the user to decide whether to import dynamically or at build time, especially since the syntax using `load` might be a little confusing for people who are new to vue / web development.

**Comment by phonzammi** [comment]
Hi @4350pChris, thanks for creating this PR,

1. I think we don't need `ServerComponent` since this will be use only for Client component
2. we don't need to check for ssr, we can do :

```ts
<template>
  <component v-if="client" :is="ClientComponent" />
</template>

<script setup>
// ...
const client = ref(false)
onMounted(() => {
  client.value = true
})
</script>
```

lifecycle hooks such as onMounted or onUpdated will NOT be called during SSR and will only be executed on the client. Vue SSR [component-lifecycle-hooks](https://vuejs.org/guide/scaling-up/ssr.html#component-lifecycle-hooks)

**Comment by 4350pChris** [comment]
You're right. I don't know why I thought we'd need to render the fallback slot on the server, which was the reason I did it that way.

**Comment by brillout** [comment]
> So for now, using `import.meta.env.SSR` doesn't seem to be a viable alternative.

You can use this trick to make it work:

```js
import.meta.env = { SSR: true }
if (import.meta.env.SSR) {
  // ...
} else {
  // ...
}
```

FYI the trick is needed because, for the server-side, Vite (usually) doesn't transpile code living inside `node_modules/`.

> `ClientOnly` should imo accept a default slot as well

Makes sense.

> the syntax using `load` might be a little confusing

How about we showcase following instead:

```vue
<ClientOnly :load="() => import('../../components/Counter.vue')">
```

That's a lot simpler than going over `<script setup>`.

My worry about using the default slot is that, because it's simpler, users are incentivized to use the default slot. So we incentivize the user to bloat their server-side with client-only components.

**Comment by 4350pChris** [comment]
Yes, I had that thought about the default slot as well. I think this is a question of whether we want to give full flexibility to the user or limit them to what imo is the better approach 99% of the time (i.e. using `load`).

As for `import.meta.env.SSR`, I'll try that.

And as for showcasing with an inline import, I think that makes sense. However, I'm using a delay so that the loading doesn't happen too fast and you can see what's going on. So maybe I'll just add one that showcases the simplest usage?

**Comment by brillout** [comment]
> Yes, I had that thought about the default slot as well. I think this is a question of whether we want to give full flexibility to the user or limit them to what imo is the better approach 99% of the time (i.e. using `load`).

Yea... the thing is that I don't see much of a use case for not wanting to load the component only on the client-side. But, if we can think of a use case, then maybe we can keep the default slot while showing a warning in the docs.

How about this: if we can think of a use case then let's keep the default slot, otherwise we remove it and only implement it if a user comes up with a use case.

So far I can't think of a use case.

> And as for showcasing with an inline import, I think that makes sense. However, I'm using a delay so that the loading doesn't happen too fast and you can see what's going on. So maybe I'll just add one that showcases the simplest usage?

Makes sense.

~~Alternatively, we could implement and showcase a `importWithDelay()`.~~ Actually, it's a bad idea as it breaks Vite's code splitting (it would actually even brak the app in most cases).

```vue
<ClientOnly :load="() => importWithDealy('../../components/Counter.vue', 2000)">
```

Let's go for your suggestion instead then 👍

**Comment by 4350pChris** [comment]
Yeah I think you're right. I'll remove the default slot for now.

And as for `client = !import.meta.env.SSR` I just remembered that we can't do it that way because it would lead to hydration mismatches as the server doesn't render anything while the client renders the fallback slot. So we need to wait for `onMounted` anyways.
Also, `import.meta.env` is read-only and TS prevents me from overwriting it like that.

**Comment by brillout** [comment]
> breaks because the path isn't included directly in an import statement? 

Exactly.

**Comment by 4350pChris** [comment]
I've got nothing more to add for now. LGTM

**Comment by phonzammi** [comment]
@4350pChris Have you export it? 
So user can do 
`import { ClientOnly } from 'vike-vue'` 
or from `'vike-vue/component'`

**Comment by 4350pChris** [comment]
@phonzammi No, I haven't. Thanks for reminding me. However, I think I need some help - right now `ClientOnly` isn't even included in `dist`. I tried adding it to `exports` in `package.json` but that doesn't change anything.

**Comment by brillout** [comment]
> Another thing that's out of scope - if we're exporting Vue components, it might make sense to switch from `tsc` to `vue-tsc`. Maybe that's what we need anyways for the component to be compiled and included in `dist`?

I'm realizing this PR introduces the first `.vue` file, so indeed we now need something like `vue-tsc`. Is it a simple change and can we just replace `$ tsc` / `$ tsc --watch` with `$ vue-tsc` / `$ vue-tsc --watch`?

Unrelated: correct me if I'm wrong, but I'm realizing that we don't need the error fallback. I think we can (and should) assume that the dynamic import will succeed. I'd argue that if it fails then it's a Vike bug, not a user land bug. The exception being when the user goes offline, but then Vike shows the error page which I think is a good solution.

One last thing: maybe we can use the default slot as the loading fallback slot. WDYT?

**Comment by 4350pChris** [comment]
I agree with the error component. Let's get rid of that.
However, I don't think we should use the default slot for the fallback as it might be confusing - when using the `ClientOnly` component from vitepress / vuepress / Nuxt the default slot is used for the component that should be shown, i.e. what our `load()` resolves to. So I think it might be better to make it obvious that the component you're passing in the template is **not** the on you want to render dynamically.

As for compilation, unfortunately `vue-tsc` doesn't support emitting files, which means we'll have to use vite and its library mode in order to compile Vue files. I tried setting it up but couldn't get it working right now as it complains about the imports from `vike/server` in `onRenderHtml.ts`. I'll take another look at it but might need some help on this one.

**Comment by brillout** [comment]
How about we create a PR for it? It's probably easier to discuss in a PR. If it works and there aren't any major issues with it, then we can quickly merge and see later down the line if it works out for us.

**Comment by 4350pChris** [comment]
Needs #62

**Comment by brillout** [comment]
> However, I don't think we should use the default slot for the fallback as it might be confusing - when using the `ClientOnly` component from vitepress / vuepress / Nuxt the default slot is used for the component that should be shown, i.e. what our `load()` resolves to. So I think it might be better to make it obvious that the component you're passing in the template is **not** the on you want to render dynamically.

Good point 👍 Ok, let's keep it a named slot then.

**Comment by 4350pChris** [comment]
So, I just updated the build since the other PR has been merged.
Should we import from `vike-vue/ClientOnly`? I implemented it like that as it was the easiest thing to do for now, however, I think I'd prefer importing from `vike-vue/components`. I guess that would mean I have to create an `index.ts` file that exports all (future) components, right?

**Review by AurelienLourot — APPROVED** [review]
LGTM, thanks!

> I think I'd prefer importing from `vike-vue/components`

I just had a talk with @brillout and we think you're right, that would be more elegant, but we're wondering how this behaves in development in terms of performance / memory consumption. (If the user imports 1 of 50 components that are all in the same file, we suspect Vite will load the whole file.)

If you want you can explore this and see how this behaves, or we can merge as is for now if you don't feel like doing that. Also if we decide to change the way we import `ClientOnly` in `vike-vue`, I'd like to align `vike-react`. We're trying to keep all the `vike-*` extensions in line as far as we can.

**Comment by 4350pChris** [comment]
As far as I understand you're right - one imported component will lead to all files being loaded. Let's merge this for now and maybe reconsider in the future when the need arises.

**Review by AurelienLourot — APPROVED** [review]

**Comment by brillout** [comment]
@4350pChris I'm currently writing proper docs for `vike-{react,vue,solid}`. One thing that is missing are Vue docs at [vike.dev/ClientOnly](https://vike.dev/ClientOnly). Up for a PR?

**Comment by 4350pChris** [comment]
@brillout Will do.

**Pull request merged**
