### PR TITLE
fix: make bodyHtml{Start,End} a global setting (fix #146)

### LINKED ISSUE #146: Setting the bodyHtmlBegin property breaks the page functionality
### Description

import vikeVue from "vike-vue/config";
import type { Config } from "vike/types";
import Head from "../layouts/HeadDefault.vue";
import Layout from "../layouts/LayoutDefault.vue";

// Default config (can be overridden by pages)
export default {
  Layout,
  Head,
  // <title>
  //# BATI.has("auth0") || BATI.has("firebase-auth") || BATI.has("authjs")
  passToClient: ["user"],
  title: "My Vike App",
  extends: vikeVue,
  stream: "web",
  bodyHtmlEnd: '<div class="test">1111111</div>',
} satisfies Config;

After switching pages, all clicking and other functions became invalid
[my-app.zip](https://github.com/user-attachments/files/16310247/my-app.zip)

### PR DESCRIPTION
**Pull request by brillout**

### CODE REVIEW

**Comment by 4350pChris** [comment]
@brillout Can this be merged? Looks good to me.

**Comment by brillout** [comment]
Mostly yes, the only thing missing is to make it cumulative.

**Comment by 4350pChris** [comment]
I don't quite understand - aren't we doing that already?

**Comment by brillout** [comment]
Ah, my bad, I thought you were commenting the other PR.

As for this PR I didn't merge it yet because of the following.

I want to create a new meta config:

```js
// +config.js

export default {
  meta: {
    bodyHtmlStart: {
       env: { server: true, client: false },
       cumulative: true,
       global: true
    }
  }
}
```

If the user sets `bodyHtmlStart` in a non-global fashion then Vike throws an helpful error. (As it wouldn't work and catching bugs early is better here.)

Also it's a breaking change, so I'm considering bundling this change with other breaking changes I'm going to release soon.

That said, I don't have any strong opinions here and I guess we could already merge since the current implementation is broken.

**Comment by 4350pChris** [comment]
Agree. Still, if this doesn't need any work I propose we merge and release once those changes are implemented. The head settings will warrant their own release as well and they're probably breaking as well so I don't see any reason to let this PR sit.

**Pull request merged**
