### PR TITLE
Improve Hooks

### PR DESCRIPTION
**Pull request by 4350pChris**
## Changes

* rename `onBeforeMountApp` to `onBeforeRenderClient`

### CODE REVIEW

**Comment by 4350pChris** [comment]
@brillout I think I'll go ahead with this API if you don't have any objections.

**Comment by brillout** [comment]
:+1: LGTM. Do some users use these hooks? If yes then we should add some `fix:` with `BREAKING CHANGE:` commit.

**Comment by 4350pChris** [comment]
> 👍 LGTM. Do some users use these hooks? If yes then we should add some `fix:` with `BREAKING CHANGE:` commit.

Like this? [589e8a4](https://github.com/vikejs/vike-vue/pull/96/commits/589e8a41d1c5a097914a53c9bffbbb66d0e01062)

**Comment by brillout** [comment]
Yes, I'd also mention that all packages need to be updated at the same time.

(The commit will appear in all three `CHANGELOG.md` because the commit touches files in all three packages.)

**Comment by brillout** [comment]
Also maybe mentioning `isHydration`.

**Comment by 4350pChris** [comment]
> Also maybe mentioning `isHydration`.

Lmk if you think this is enough.

**Comment by brillout** [comment]
It'll probably lead to a couple of users having to spend more time on migration, but I think it's ok.

Free free to merge & publish.

**Pull request merged**
