### PR TITLE
fix: further ensure Vue doesn't swallow errors

### PR DESCRIPTION
**Pull request by brillout**

### CODE REVIEW

**Review by phonzammi — CHANGES_REQUESTED** [review]
Hi @brillout , don't forget to change if necessary
`ReturnType<typeof renderToNodeStream>` 
to 
`ReturnType<typeof renderToNodeStream_>`,

**Comment by brillout** [comment]
@phonzammi I've another little minor refactoring idea; if it's ok with you I'll create a seperate PR for it after this one is merged. (@AurelienLourot the converstion about `ReturnType<typeof renderToNodeStream>` is unrelated to this PR and you can ignore it.)

**Comment by phonzammi** [comment]
@brillout , yes please

**Review by AurelienLourot — APPROVED** [review]
Ah I see, nice catch. LGTM :+1:

**Pull request merged**
