### PR TITLE
feat: export Vike configuration at /config #92

### LINKED ISSUE #92: Export Vike configuration at `/config`
```diff
  import type { Config } from 'vike/types'
  import vikeVue from 'vike-vue/config'
- import vikePinia from 'vike-pinia'
+ import vikePinia from 'vike-pinia/config'

  export default {
    extends: [vikeVue, vikePinia],
  } satisfies Config
```

Same for `vike-vue-query`.

### PR DESCRIPTION
**Pull request by pdanpdan**
- export Vike configuration at /config for vike-pinia and vike-vue-query
- export configuration as default in vike-vue

close #92

### CODE REVIEW

**Comment by brillout** [comment]
Neat :+1: 

If we break down the commit in two commits, then `@brillout/release-me` will correctly update all the `CHANGELOG.md` files:
 1. A commit that only touches `packages/vike-vue` (without `fix:` commit message prefix)
 2. A commit that only touches `packages/vike-{vue-query,pinia}` (with `fix:` prefix and a second commit message line `BREAKING CHANGE:`)
 
After merging, I'll bump and release a new major for `vike-{vue-query,pinia}`.

On a tangent @4350pChris and myself where thinking of renaming `vike-pinia` to `vike-vue-pinia` to keep things consistent. I think we can do this at some point later.

**Comment by pdanpdan** [comment]
Sure, it makes sense. Just let me check something about a hydration error in `vike-vue-query` before, because I was on it.

**Comment by pdanpdan** [comment]
can you please check if it looks ok as it is split now?

**Comment by brillout** [comment]
Yes, LGTM. Can I merge & release?

**Comment by pdanpdan** [comment]
You can merge. For release should we also change the name of the package first?

**Comment by brillout** [comment]
> For release should we also change the name of the package first?

As you wish.

@4350pChris WDYT?

**Comment by brillout** [comment]
Maybe it would be nice to do it, so we have it behind us :heavy_check_mark:

**Comment by 4350pChris** [comment]
Go ahead and change it 👍

**Comment by brillout** [comment]
`vike-vue-query@0.0.3` released.

**Comment by brillout** [comment]
I wonder why the CI wasn't triggered for this PR :thinking:

I was under the impression the following would work: https://github.com/vikejs/vike-vue/blob/b3c0cb2df9d4e30540315dc36d9a73026a243fbc/.github/workflows/ci.yml#L2-L7

**Pull request merged**
