### PR TITLE
reproduce for #184

### PR DESCRIPTION
**Pull request by phonzammi**

### CODE REVIEW

**Comment by brillout** [comment]
It doesn't seem to be a bug though? The page's title is correctly set to `changed`.

**Comment by phonzammi** [comment]
> The page's title is correctly set to `changed`.

Yeah, it is. It's because `useConfig()` returns/calls `setPageContextConfigFromHook()` which calls `Object.assign(pageContext._configFromHook, config)` and finally `applyHeadSettings()` gets the title from `pageContext._configFromHook`.

IMO, isn't it should just calls `apply(config)` on the page navigation ?

If it's okay, than maybe we don't need [apply(config)](https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/hooks/useConfig/useConfig-client.ts#L20) function ?

**Comment by brillout** [comment]
I'm still not sure what problem this is trying to address. That's why my thinking is that, if you can show that there is a bug (e.g. with a reproduction or step-by-step instructions), then this would make it clear what your goal is.

I may very well be missing something but, so far, I'm still thinking that everything works as expected.

One thing you rightfully point to is the fact that there is duplicated logic. [I went ahead and remove the duplication](https://github.com/vikejs/vike-vue/commit/0dc8b21dd6e8026f7856fa8c4168ebfbd2b9127a). Thanks!

**Comment by brillout** [comment]
> If it's okay, than maybe we don't need [apply(config)](https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/hooks/useConfig/useConfig-client.ts#L20) function ?

We need it for example when the user uses React's `useState()`. (Same for Vue; Dan recently made a Vue example of a stateful component using `useConfig()`.)

I think the priority for now should be to make the implemention accurate. There are a *lot* of open questions around head management, so I'm inclined to first focus on accuracy and supporting the most common use cases (while [enabling users to implement their own settings](https://vike.dev/head-tags#custom-settings) for edge use cases).

**Comment by phonzammi** [comment]
> I think the priority for now should be to make the implemention accurate. There are a _lot_ of open questions around head management, so I'm inclined to first focus on accuracy

Yes, that’s what I’m trying to address here

**Comment by phonzammi** [comment]
Let's say we have a use case like the following :
* A user sets a `title` inside a `+config.js` file.
* A user also sets a `title` inside a component (`/index/+Page.vue`) by using `useConfig()` hook.

My question is: What should the execution order be ?
1. When a user visits `/` page for the first time (`isHydration` is `true`). Right now it is :
 ```
config() -> applyHead() -> applyHeadSettings()
```
2. When a user navigates to other page than navigates back to `/` page (`isHydration` is `false`). Right now it is:
```
config() -> setPageContextConfigFromHook() -> onRenderClient applyHead() -> applyHeadSettings()
```

**Comment by brillout** [comment]
Hm, I still think it works as it should. But if you can find a bug then I'm more than happy to dig more into it :eyes: Closing in the meantime.

**Pull request closed without merging**
